### ISSUE TITLE
Qoreidsdk android launch crash flutter app

### ISSUE THREAD

**Issue by michael-timi** [QoreID/qoreid_flutter_example#2]
We've setup the qoreidsdk on our app for close to a year but for the last two months, we've been getting a series of reports of it crashing on our flutter android app on launching it to initialize a KYC process.

It doesn't occur on all android devices though 

![Screenshot_2024-06-26-20-17-06-703_com.miui.bugreport.jpg](https://github.com/QoreID/qoreid_flutter_example/assets/47628001/948a1dff-571e-40b3-a856-769067845eb5)

**Comment by ScribbleTons** [comment]
Hi, could you send a screenshot of the error message?

If possible, update the plugin.

**Comment by michael-timi** [comment]
![Screenshot_2024-06-26-20-17-06-703_com.miui.bugreport.jpg](https://github.com/QoreID/qoreid_flutter_example/assets/47628001/1ad64fea-7b5e-473d-a8eb-00b7169a5164)

**Comment by michael-timi** [comment]
I've updated the package but the issue still persists

**Comment by ScribbleTons** [comment]
Kindly send us a message via the companies email. You account manager
should have the details.
